/* Spatial Studio: explicit local references + host-owned offline motion analysis. */
(() => {
  'use strict';
  const C=window.OsmoSpatialCore;
  let viewerLoad;
  function loadViewer(){if(window.createSpatialView)return Promise.resolve();return viewerLoad||(viewerLoad=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='/vendor/spatial-view.js';s.onload=resolve;s.onerror=()=>{viewerLoad=null;reject(Error('3D module unavailable. The 2D rehearsal remains usable.'));};document.head.append(s);}));}
  const number=(v,fallback=0)=>Number.isFinite(+v)?+v:fallback;
  const clone=x=>structuredClone(x);
  function download(body,name,type){const u=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  window.createSpatialStudio=(root,api)=>{
    root.innerHTML=`<div class="sp-heading"><div><small>DIRECTOR · SPATIAL REHEARSAL</small><h2>See the shot before you shoot.</h2></div><span class="sp-badge">PREVIEW ONLY</span></div>
      <div class="sp-toolbar"><button data-action="refresh" title="Analyse the current draft without contacting the camera">↻ Load current shot</button><button data-action="enable">◈ Enable 3D</button><select id="spView" aria-label="Rehearsal view"><option value="frame">Frame</option><option value="overview">Where the camera looks</option><option value="compare">Compare A / B</option><option value="flat">2D path</option></select></div>
      <div class="sp-stage"><div id="spViewport" aria-label="Approximate spatial rehearsal"></div><canvas id="spFlat" role="img" aria-label="Rotation-only path; numerical beat positions follow below"></canvas><div id="spFrameGuide" aria-hidden="true"></div><span id="spStageLabel">Reference imagery is optional. Unknown areas remain blank.</span></div>
      <div class="sp-transport"><button id="spPlay" data-action="play">▶ Rehearse</button><button data-action="start" title="Return the virtual playhead to the beginning">↤</button><input id="spScrub" type="range" min="0" max="1" step=".01" value="0" aria-label="Spatial rehearsal time"><output id="spTime">0.00 s</output></div>
      <p id="spStatus" role="status" aria-live="polite">Load a shot with at least two positions. No camera connection is needed.</p><div id="spBeats" class="sp-beats"></div>
      <nav class="sp-tabs" aria-label="Spatial tools"><button data-tab="location">▧ Location</button><button data-tab="marks">◎ Framing</button><button data-tab="feel">≈ Motion feel</button><button data-tab="takes">⌁ Take ghost</button><button data-tab="recipes">◇ Recipes</button><button data-tab="share">↗ Share</button></nav>
      <section data-section="location"><h3>Location memory</h3><p>Images stay in this browser. They are never sent to AI or the host. Saved camera angles are not a surveyed room.</p>
        <div class="sp-fields"><label>Location name<input id="spName" maxlength="128" value="Untitled location"></label><label>Saved locations<select id="spLocations"><option value="">Choose a location</option></select></label></div>
        <div class="sp-actions"><button data-action="save">Save locally</button><button data-action="load">Open saved</button><button data-action="new">New location</button><button data-action="delete">Delete saved</button></div>
        <div class="sp-fields"><label>Captured horizontal field of view · assumed<input id="spFov" type="number" min="10" max="150" step=".1" value="84"></label><label>Capture frame<select id="spCaptureAspect"><option value="1.7777777777777777">16:9 landscape</option><option value="0.5625">9:16 portrait</option><option value="1.3333333333333333">4:3</option></select></label><label>Delivery crop<select id="spAspect"><option value="1.7777777777777777">16:9 landscape</option><option value="0.5625">9:16 portrait</option><option value="1">Square</option><option value="2.39">2.39:1 cinema</option></select></label><label>Margin at each edge · %<input id="spMargin" type="number" min="0" max="40" value="10"></label></div>
        <div class="sp-fields"><label>Reference position<select id="spPoint"></select></label><label>Still image<input id="spStill" type="file" accept="image/jpeg,image/png,image/webp"></label><label>360° panorama · 2:1 image<input id="spPano" type="file" accept="image/jpeg,image/png,image/webp"></label></div>
        <div class="sp-actions"><button data-action="snapshot" title="Read an already-running camera preview. Does not start live view, move or take a photograph.">▣ Attach camera preview</button><button data-action="clear-pano">Remove panorama</button></div>
        <div class="sp-fields"><label>Panorama centre pan · °<input id="spPanoYaw" type="number" min="-3600" max="3600" step=".1" value="0"></label><label>Panorama centre tilt · °<input id="spPanoPitch" type="number" min="-3600" max="3600" step=".1" value="0"></label></div>
        <p>Align the image centre to a known framing. Re-check after moving the tripod, restarting the rig or changing lens/crop. Zoom, roll and camera travel are not simulated. Perspective and depth are not calibrated; preview stills and attitude are not synchronised.</p><div id="spReferences" class="sp-references"></div>
      </section>
      <section data-section="marks" hidden><h3>Reveal choreography & framing protection</h3><p>Mark fixed subjects or things to keep out of frame. Checks are sampled estimates using your field of view—not tracking or a safety guarantee.</p>
        <div class="sp-fields"><label>Mark name<input id="spMarkName" maxlength="128" placeholder="Product logo"></label><label>Intent<select id="spMarkKind"><option value="subject">Reveal subject</option><option value="avoid">Keep out of frame</option></select></label><label>Pan · °<input id="spMarkYaw" type="number" min="-3600" max="3600" step=".1" value="0"></label><label>Tilt · °<input id="spMarkPitch" type="number" min="-3600" max="3600" step=".1" value="0"></label><label>Do not reveal before · s<input id="spNotBefore" type="number" min="0" max="86400" step=".1" value="0"></label><label>Visible hold requested · s<input id="spHold" type="number" min="0" max="3600" step=".1" value="0"></label></div>
        <div class="sp-actions"><button data-action="mark-pose">Use virtual framing</button><button data-action="add-mark">＋ Add mark</button><button data-action="check">Check framing</button></div>
        <div id="spMarks"></div><div id="spChecks"></div><details><summary>Make a reveal treatment</summary><p>Choose a mark below, then assign it to an existing framing point. This creates a draft proposal, not live movement. Hold and travel time are editable before applying.</p><div class="sp-fields"><label>Subject<select id="spRevealMark"></select></label><label>Existing point<select id="spRevealPoint"></select></label><label>Travel time · s<input id="spRevealTime" type="number" min=".1" max="3600" value="6" step=".1"></label></div><button data-action="reveal">Preview reveal treatment</button></details>
      </section>
      <section data-section="feel" hidden><h3>Motion feel · A / B</h3><p>A is the loaded draft. B is an unapplied timing or reveal treatment. Both share elapsed program time; the shorter version holds its last frame. Operator cues still pause rehearsal.</p>
        <div class="sp-fields"><label>Travel time multiplier<input id="spTempo" type="number" min=".25" max="4" step=".05" value="1.25"></label><label>Fixed holds multiplier<input id="spDwell" type="number" min="0" max="4" step=".1" value="1"></label><label>Movement feel<select id="spEase"><option value="keep">Keep authored easing</option><option value="linear">Linear</option><option value="ease-in-out">Ease in / out</option><option value="ease-in">Ease in</option><option value="ease-out">Ease out</option></select></label></div>
        <button data-action="treatment">Build B treatment</button><div id="spReadability"></div><div id="spCandidate"></div><div class="sp-actions"><button id="spApply" data-action="apply" disabled>Apply B to draft</button><button id="spUndo" data-action="undo" disabled>↶ Restore previous draft</button><button data-action="discard">Discard B</button></div>
      </section>
      <section data-section="takes" hidden><h3>Take ghost</h3><p>Cyan is the plan; amber is reported camera direction. Gaps over one second remain broken. No translation, optical stability or pixel-perfect repeatability is inferred.</p><div class="sp-actions"><button data-action="takes">Load take list</button><select id="spTake" aria-label="Take trace"></select><button data-action="ghost">Show reported trace</button><button data-action="clear-ghost">Hide trace</button><button data-action="settle">Inspect reported settling</button></div><div id="spSettle"></div></section>
      <section data-section="recipes" hidden><h3>Shot recipes</h3><p>Keep the rhythm, replace the location. A recipe maps names, travel times, holds and easing onto the same number of existing points. Angles, zoom, cues and rig settings stay untouched.</p><div class="sp-fields"><label>Recipe name<input id="spRecipeName" maxlength="128" placeholder="Detail → reveal → hero"></label><label>Saved recipe<select id="spRecipe"></select></label></div><div class="sp-actions"><button data-action="save-recipe">Save current rhythm</button><button data-action="recipe">Preview recipe as B</button><button data-action="delete-recipe">Delete recipe</button></div><div id="spRoles"></div></section>
      <section data-section="share" hidden><h3>Storyboard & portable location</h3><p>Export files deliberately. No upload, tracking scripts or camera controls are included. Sharing reference imagery is optional.</p><label class="sp-check"><input id="spIncludeImages" type="checkbox">Include reference images in storyboard</label><div class="sp-actions"><button data-action="storyboard">Export storyboard HTML</button><button data-action="export">Export location with images</button><label>Import location file<input id="spImport" type="file" accept="application/json,.json"></label></div></section>`;
    const $=id=>root.querySelector('#'+id), status=s=>$('spStatus').textContent=s;
    let scene=C.empty(),view=null,base=null,analysis=null,variant=null,variantAnalysis=null,undo=null,undoSig=null;
    let ticket=0,time=0,playing=false,raf=0,last=0,lastDraw=0,cues=new Set(),waiting=null,ghost=[],takes=[],busy=false;
    const signature=()=>JSON.stringify(api.getMove()), reduced=matchMedia('(prefers-reduced-motion: reduce)');
    const end=()=>Math.max(analysis?.display_samples?.at(-1)?.time||0,variantAnalysis?.display_samples?.at(-1)?.time||0);
    const pose=()=>C.sampleAt(analysis?.display_samples,time);
    const options=()=>({...C.framing(scene),margin:scene.margin,markers:scene.markers});
    function pause(){playing=false;cancelAnimationFrame(raf);$('spPlay').textContent=waiting?'Continue cue':'▶ Rehearse';}
    function invalidate(){ticket++;pause();analysis=base=variant=variantAnalysis=null;undo=null;undoSig=null;ghost=[];time=0;waiting=null;cues.clear();$('spApply').disabled=$('spUndo').disabled=true;render();status('Draft changed. Load the current shot to rehearse it. Local reference images are preserved.');}
    async function request(body){const result=await api.post('/api/spatial/preview',body);if(!result.ok)throw Error(result.error||'Analysis unavailable.');return result;}
    async function refresh(){checkInputs();pause();const n=++ticket,shot=clone(api.getMove()),sig=signature();const result=await request({move:shot,options:options()});if(n!==ticket||sig!==signature())return;
      base=shot;analysis=result.spatial;variant=variantAnalysis=null;time=0;waiting=null;cues.clear();$('spApply').disabled=true;lists();render();status('Current shot loaded. Field of view and imagery remain approximate. Camera unchanged.');}
    function checkInputs(){const next=clone(scene);next.name=$('spName').value.trim()||'Untitled location';next.hfov=number($('spFov').value);next.captureAspect=number($('spCaptureAspect').value);next.aspect=number($('spAspect').value);next.margin=number($('spMargin').value)/100;if(next.panorama){next.panorama.yaw=number($('spPanoYaw').value);next.panorama.pitch=number($('spPanoPitch').value);}scene=C.validate(next);}
    function fields(){for(const [id,key] of [['spName','name'],['spFov','hfov'],['spCaptureAspect','captureAspect'],['spAspect','aspect']]){$(id).value=scene[key];if(!$(id).value&&$(id).tagName==='SELECT'){$(id).add(new Option('Custom ratio '+scene[key].toFixed(3),scene[key]));$(id).value=scene[key];}}$('spMargin').value=scene.margin*100;$('spPanoYaw').value=scene.panorama?.yaw||0;$('spPanoPitch').value=scene.panorama?.pitch||0;}
    function select(el,rows,label){const old=el.value;el.replaceChildren();rows.forEach((r,i)=>el.add(new Option(label(r,i),i)));if([...el.options].some(o=>o.value===old))el.value=old;}
    function lists(){
      const points=(base||api.getMove()).waypoints||[];for(const id of ['spPoint','spRevealPoint'])select($(id),points,(p,i)=>`P${i+1} · ${p.name||'Framing'}`);
      select($('spRevealMark'),scene.markers,m=>m.name);select($('spRecipe'),scene.recipes,r=>r.name);
      $('spReferences').replaceChildren();scene.references.forEach((r,i)=>{const item=document.createElement('article'),img=new Image();img.src=r.url;img.alt=r.name;const b=document.createElement('button');b.textContent='Remove';b.onclick=()=>{scene.references.splice(i,1);lists();render();status('Reference removed in this working location. Save to retain the change.');};const name=document.createElement('span');name.textContent=`${r.name} · ${r.yaw.toFixed(1)}° / ${r.pitch.toFixed(1)}°`;item.append(img,name,b);$('spReferences').append(item);});
      $('spMarks').replaceChildren();scene.markers.forEach((m,i)=>{const row=document.createElement('p'),b=document.createElement('button');row.textContent=`${m.kind==='avoid'?'Keep out':'Reveal'} · ${m.name} · ${m.yaw.toFixed(1)}° / ${m.pitch.toFixed(1)}° `;b.textContent='Remove';b.onclick=()=>wrapped(async()=>{scene.markers.splice(i,1);if(base)await refresh();else{lists();render();}});row.append(b);$('spMarks').append(row);});
      $('spRoles').replaceChildren();const recipe=scene.recipes[+$('spRecipe').value];if(recipe)for(const [i,r] of recipe.roles.entries()){const p=document.createElement('p');p.textContent=`P${i+1}: ${r.name} · travel ${r.duration}s · hold ${r.dwell}s · ${r.easing}`;$('spRoles').append(p);}
    }
    function flat(){const c=$('spFlat'),w=Math.max(1,c.clientWidth),h=Math.max(1,c.clientHeight),d=Math.min(devicePixelRatio||1,1.5);if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d);}const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b1520';ctx.fillRect(0,0,w,h);
      const points=analysis?.display_samples||[];if(!points.length){ctx.fillStyle='#a8bdcc';ctx.textAlign='center';ctx.font='14px system-ui';ctx.fillText('Load a shot to begin',w/2,h/2);return;}
      const all=[...points,...(variantAnalysis?.display_samples||[]),...ghost.flat()],xs=all.map(p=>p.yaw),ys=all.map(p=>p.pitch),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=Math.min((w-60)/Math.max(10,maxX-minX),(h-60)/Math.max(10,maxY-minY));const xy=p=>[w/2+(p.yaw-(minX+maxX)/2)*scale,h/2-(p.pitch-(minY+maxY)/2)*scale];
      ctx.strokeStyle='#304352';for(let x=20;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}ctx.strokeStyle='#7ee2dd';ctx.lineWidth=2;ctx.beginPath();points.forEach((p,i)=>{const q=xy(p);i?ctx.lineTo(...q):ctx.moveTo(...q);});ctx.stroke();const p=pose();if(p){ctx.fillStyle='#e9fdf9';ctx.beginPath();ctx.arc(...xy(p),6,0,Math.PI*2);ctx.fill();}
      ctx.strokeStyle='#ffc071';for(const segment of ghost){ctx.beginPath();segment.forEach((p,i)=>{const q=xy(p);i?ctx.lineTo(...q):ctx.moveTo(...q);});ctx.stroke();}
      const b=C.sampleAt(variantAnalysis?.display_samples,time);if(b){ctx.strokeStyle='#bb9df7';ctx.lineWidth=3;ctx.strokeRect(xy(b)[0]-7,xy(b)[1]-7,14,14);}
    }
    function viewData(){return {samples:analysis?.display_samples||[],waypoints:base?.waypoints||[],references:scene.references,panorama:scene.panorama,markers:scene.markers,ghostSegments:ghost,...C.framing(scene)};}
    function guide(){const box=$('spViewport'),w=Math.min(box.clientWidth,box.clientHeight*scene.aspect),h=w/scene.aspect;$('spFrameGuide').style.width=w*(1-2*scene.margin)+'px';$('spFrameGuide').style.height=h*(1-2*scene.margin)+'px';}
    function draw(){const p=pose();if(view){view.setPose(p||{pitch:0,yaw:0},C.sampleAt(variantAnalysis?.display_samples,time));}guide();flat();$('spScrub').value=time;$('spTime').textContent=time.toFixed(2)+' s';}
    function render(){
      const isFlat=!view||$('spView').value==='flat';$('spFlat').hidden=!isFlat;$('spViewport').hidden=isFlat;$('spFrameGuide').hidden=isFlat||$('spView').value!=='frame';
      $('spScrub').max=end()||1;$('spPlay').disabled=!analysis?.display_samples?.length;$('spScrub').disabled=$('spPlay').disabled;
      $('spStageLabel').textContent=$('spView').value==='compare'?'A · Loaded draft     /     B · Unapplied treatment · Same elapsed time':$('spView').value==='overview'?'Pointing directions only · Cyan plan / amber reported':'Approximate field of view · Blank areas have no reference imagery';
      if(view){view.setMode($('spView').value==='flat'?'frame':$('spView').value);view.setData(viewData());}draw();$('spBeats').replaceChildren();
      for(const b of analysis?.preview?.beats||[]){if(b.direction!=='forward')continue;const button=document.createElement('button');button.textContent=`P${b.index+1} ${b.name||''} · ${b.arrival.toFixed(1)}s`;button.title=`Pan ${base.waypoints[b.index].yaw}°, tilt ${base.waypoints[b.index].pitch}°. Virtual preview only.`;button.onclick=()=>seek(b.arrival);$('spBeats').append(button);}
      $('spChecks').replaceChildren();for(const [label,result] of [['A',analysis],['B',variantAnalysis]])for(const m of result?.projection?.markers||[]){const p=document.createElement('p'),region=m.kind==='avoid'?'delivery frame':'protected inner frame';p.textContent=`${label} · ${m.name}: ${m.first_visible===null?'not inside the '+region+' in sampled frames':`inside ${region} at ${m.intervals.map(v=>v.start.toFixed(2)+'–'+v.end.toFixed(2)+'s').join(', ')} · ${m.visible_seconds.toFixed(2)}s total`}${m.violates_reveal?' · Review framing intent':''}`;$('spChecks').append(p);}
      const rate=value=>Number.isFinite(value)?value.toFixed(2):'unavailable';
      $('spReadability').textContent=analysis?[['A',analysis],['B',variantAnalysis]].filter(([,r])=>r).map(([label,r])=>`${label}: estimated peak pace ${rate(r.projection.readability.horizontal_screen_widths_per_second)} frame widths/s, ${rate(r.projection.readability.vertical_frame_heights_per_second)} frame heights/s.${r.display_resolution_limited?' Long shot: visual sampling is reduced.':''}`).join(' ')+' Sampled angle/FOV heuristic, not judder or blur certification.':'';
    }
    function seek(t){pause();waiting=null;time=Math.max(0,Math.min(end(),t));cues=new Set(C.cueEvents(analysis,variantAnalysis).filter(e=>e.time<time).map(e=>e.key));draw();}
    function tick(now){if(!playing)return;const next=Math.min(end(),time+(now-last)/1000);last=now;const ev=C.cueEvents(analysis,variantAnalysis).find(e=>!cues.has(e.key)&&e.time>=time-1e-5&&e.time<=next);
      if(ev){time=ev.time;waiting=ev;pause();draw();status('Operator cue in '+ev.lane+' at '+(ev.name||'framing')+'. Continue rehearsal when ready. Live wait duration is unknown.');return;}
      time=next;if(!reduced.matches||now-lastDraw>=500||time>=end()){draw();lastDraw=now;}if(time>=end()){pause();return;}raf=requestAnimationFrame(tick);}
    async function treatment(shot,recipe){if(!base||signature()!==JSON.stringify(base))throw Error('Load the current shot first.');pause();const n=++ticket,sig=signature();const r=await request({move:shot,options:options(),...(recipe?{recipe}: {})});if(n!==ticket||signature()!==sig)return;
      variant=r.move;variantAnalysis=r.spatial;const ok=variantAnalysis.preview.preflight.ok;$('spApply').disabled=!ok;$('spCandidate').textContent=(ok?'B passed sampled motion checks. ':'B needs revision: ')+variantAnalysis.preview.preflight.findings.map(f=>f.detail).join(' ')+(variantAnalysis.projection.markers.some(m=>m.violates_reveal)?' Framing intent is not satisfied; inspect the Framing tab.':'');$('spView').value=view?'compare':'flat';seek(0);render();status('B ready to compare. It has not changed your draft or camera.');}
    async function ensure3D(){await loadViewer();if(view){view.setActive(true);return;}view=createSpatialView($('spViewport'),{onPick:p=>{$('spMarkYaw').value=p.yaw.toFixed(2);$('spMarkPitch').value=p.pitch.toFixed(2);status('Direction selected for a mark. Nothing has moved.');},onError:m=>{queueMicrotask(()=>{status(m+' Use 2D path or re-enable 3D.');view?.dispose();view=null;$('spView').value='flat';render();});}});$('spView').value='frame';render();}
    async function locations(){const names=await C.storage('list');$('spLocations').replaceChildren(new Option('Choose a location',''));names.forEach(n=>$('spLocations').add(new Option(n,n)));}
    async function wrapped(fn){if(busy)return;busy=true;root.inert=true;root.setAttribute('aria-busy','true');try{await fn();}catch(e){status(e.message||String(e));}finally{busy=false;root.inert=false;root.setAttribute('aria-busy','false');}}
    const actions={
      refresh,enable:ensure3D,play:()=>{if(playing){pause();return;}if(!analysis)return;api.pause?.();view?.setActive(true);const resumed=!!waiting;if(waiting){cues.add(waiting.key);waiting=null;}if(time>=end()&&!resumed)seek(0);playing=true;last=performance.now();$('spPlay').textContent='Ⅱ Pause';raf=requestAnimationFrame(tick);},start:()=>seek(0),
      save:async()=>{checkInputs();await C.storage('save',scene.name,scene);await locations();status('Location saved in this browser. Export a copy before changing devices.');},
      load:async()=>{if(!$('spLocations').value)throw Error('Choose a saved location.');if(!confirm('Replace this working location? Save or export unsaved references first.'))return;scene=C.validate(await C.storage('get',$('spLocations').value));fields();lists();await refresh();},
      new:()=>{if(!confirm('Start a new working location? Saved locations will remain.'))return;scene=C.empty();fields();invalidate();lists();},
      delete:async()=>{const name=$('spLocations').value;if(!name)throw Error('Choose a saved location.');if(confirm('Delete saved location “'+name+'” from this browser? Export first for a recovery copy.')){await C.storage('delete',name);await locations();status('Saved location deleted. The current working copy remains until replaced.');}},
      'clear-pano':()=>{scene.panorama=null;render();status('Panorama removed from this working location. Save to retain the change.');},
      snapshot:async()=>{const r=await fetch('/api/spatial/snapshot',{cache:'no-store',signal:AbortSignal.timeout(3000)}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Fresh preview unavailable.');if(scene.references.length>=24)throw Error('Remove a reference first (24 maximum).');const response=await fetch(j.image),file=new File([await response.blob()],'preview.jpg',{type:'image/jpeg'}),decoded=await C.decode(file);scene.references.push({name:'Preview '+(scene.references.length+1),url:decoded.url,aspect:decoded.aspect,hfov:scene.hfov,pitch:j.pitch,yaw:j.yaw});scene=C.validate(scene);lists();render();status(j.scope+' Save location to keep it.');},
      'mark-pose':()=>{const p=pose();if(!p)throw Error('Load a shot first.');$('spMarkYaw').value=p.yaw.toFixed(2);$('spMarkPitch').value=p.pitch.toFixed(2);},
      'add-mark':async()=>{scene=C.validate({...scene,markers:[...scene.markers,{name:$('spMarkName').value.trim(),kind:$('spMarkKind').value,yaw:number($('spMarkYaw').value),pitch:number($('spMarkPitch').value),not_before:number($('spNotBefore').value),hold:number($('spHold').value)}]});if(base)await refresh();else{lists();render();}status('Mark added. Framing estimates depend on the assumed FOV.');},
      check:async()=>{checkInputs();await refresh();status('Framing check updated. Estimates depend on your FOV and fixed-point alignment.');},
      reveal:async()=>{const m=scene.markers[+$('spRevealMark').value],i=+$('spRevealPoint').value;if(!m||!base?.waypoints[i])throw Error('Select a subject and an existing framing point.');if(m.kind==='avoid')throw Error('Use a reveal subject, not a keep-out mark.');const draft=clone(base);Object.assign(draft.waypoints[i],{name:m.name,pitch:m.pitch,yaw:m.yaw,duration:number($('spRevealTime').value),dwell:m.hold});await treatment(draft);tab('feel');},
      treatment:async()=>{if(!base)throw Error('Load a shot first.');const draft=clone(base),tempo=number($('spTempo').value),hold=number($('spDwell').value);if(tempo<.25||tempo>4||hold<0||hold>4)throw Error('Use travel 0.25–4× and holds 0–4×.');draft.waypoints.forEach((p,i)=>{if(i)p.duration*=tempo;p.dwell*=hold;if($('spEase').value!=='keep')p.easing=$('spEase').value;});await treatment(draft);},
      apply:async()=>{if(!variant||!variantAnalysis?.preview.preflight.ok||signature()!==JSON.stringify(base))throw Error('Treatment is stale or fails its sampled checks. Rebuild it.');if(!confirm('Apply B to the authored draft? This changes the planned shot, not the camera.'))return;const before=clone(base),next=clone(variant);if(await api.apply(next)){await refresh();undo=before;undoSig=signature();$('spUndo').disabled=false;status('B applied to the draft. Camera unchanged. Restore is available until the next edit.');}},
      undo:async()=>{if(!undo||signature()!==undoSig)throw Error('A newer edit prevents restoring this treatment.');const previous=clone(undo);if(await api.apply(previous)){await refresh();undo=null;$('spUndo').disabled=true;status('Previous draft restored.');}},
      discard:()=>{variant=variantAnalysis=null;$('spApply').disabled=true;$('spCandidate').textContent='';render();},
      takes:async()=>{const r=await fetch('/api/takes',{signal:AbortSignal.timeout(3000)});if(!r.ok)throw Error('Take list unavailable.');takes=(await r.json()).takes||[];select($('spTake'),takes,(t,i)=>`${i+1} · ${t.scene||''} ${t.shot||''}/${t.take||''}${t.motion?.trace?.length?'':' · no trace'}`);},
      ghost:()=>{const take=takes[+$('spTake').value];if(!take?.motion?.trace?.length)throw Error('This take has no reported trace.');ghost=C.ghostSegments(take.motion.trace);$('spView').value=view?'overview':'flat';render();status('Reported angular trace shown. Align the rig reference before comparing different sessions.');},
      'clear-ghost':()=>{ghost=[];render();},
      settle:async()=>{const selected=takes[+$('spTake').value];if(!selected)throw Error('Load and choose a take first.');const result=await api.post('/api/spatial/settle',{take:+$('spTake').value});if(!result.ok)throw Error(result.error);$('spSettle').replaceChildren();for(const [i,o] of result.observations.entries()){const p=document.createElement('p');p.textContent=`P${i+1}: ${o.settling_seconds===null?'insufficient contiguous evidence':o.settling_seconds.toFixed(2)+' s to observed angular quiet window'}. Not proof of image stability.`;$('spSettle').append(p);
        if(base&&JSON.stringify(selected.path||selected.motion?.path)===JSON.stringify(base)&&o.settling_seconds!==null){const hold=Math.ceil((o.settling_seconds+.25)*10)/10;if(hold>base.waypoints[i].dwell){const button=document.createElement('button');button.textContent=`Preview P${i+1} hold of ${hold.toFixed(1)}s`;button.onclick=()=>wrapped(async()=>{const proposal=clone(base);proposal.waypoints[i].dwell=hold;await treatment(proposal);tab('feel');});p.append(button);}}
      }status(result.scope||'Nominal program time; no camera action.');},
      'save-recipe':()=>{const shot=api.getMove();if(shot.waypoints.length<2||shot.waypoints.length>24)throw Error('Recipes support 2–24 existing framing points.');const r={name:$('spRecipeName').value.trim()||shot.name||'Shot rhythm',roles:shot.waypoints.map(p=>({name:p.name||'Framing',duration:p.duration,dwell:p.dwell,easing:p.easing}))};scene=C.validate({...scene,recipes:[...scene.recipes,r]});lists();status('Recipe added to this location. Save locally or export to retain it.');},
      recipe:async()=>{const r=scene.recipes[+$('spRecipe').value];if(!r)throw Error('Choose a recipe.');await treatment(base||api.getMove(),{roles:r.roles});tab('feel');},
      'delete-recipe':()=>{const i=+$('spRecipe').value;if(!scene.recipes[i])return;if(confirm('Remove this recipe from the working location?')){scene.recipes.splice(i,1);lists();}},
      export:()=>{checkInputs();download(JSON.stringify(scene,null,2),'osmodesk-location.json','application/json');status('Location exported with its reference images. Share only with intended recipients.');},
      storyboard:async()=>{
        if(!analysis)throw Error('Load a shot first.');pause();const n=ticket,shot=clone(base),beats=analysis.preview.beats.filter(b=>b.direction==='forward'),images=[],include=$('spIncludeImages').checked,oldView=$('spView').value,scroll=window.scrollY;
        try{
          if(include&&(scene.panorama||scene.references.length)){
            await ensure3D();$('spView').value='frame';render();$('spViewport').scrollIntoView({block:'center'});await view.ready();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
            for(const beat of beats.slice(0,24)){if(n!==ticket)throw Error('Draft changed during export. Reload and try again.');view.setPose(C.sampleAt(analysis.display_samples,beat.arrival));images.push(view.capture());}
          }
          if(n!==ticket)throw Error('Draft changed during export. Reload and try again.');
          download(C.storyboard({name:shot.name||scene.name,beats,images,includeImages:include,scope:`Assumed captured horizontal FOV ${scene.hfov}°. ${scene.name}. Centred ${scene.aspect.toFixed(3)}:1 delivery crop. At most 24 rendered reference frames; unpictured directions are blank. Marks are rehearsal overlays.`}),'osmodesk-storyboard.html','text/html');status('Standalone storyboard exported. No camera controls, scripts or external requests.');
        }finally{$('spView').value=oldView;render();window.scrollTo({top:scroll,behavior:'instant'});}
      }
    };
    function tab(name){root.querySelectorAll('[data-section]').forEach(s=>s.hidden=s.dataset.section!==name);root.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===name)));window.refreshStudioLayout?.('director');}
    root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>wrapped(actions[b.dataset.action]));root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
    $('spScrub').oninput=()=>seek(+$('spScrub').value);$('spView').onchange=()=>wrapped(async()=>{if($('spView').value!=='flat'&&!view){const chosen=$('spView').value;await ensure3D();$('spView').value=chosen;}render();});
    for(const id of ['spFov','spCaptureAspect','spAspect','spMargin','spPanoYaw','spPanoPitch'])$(id).onchange=()=>wrapped(async()=>{checkInputs();variant=variantAnalysis=null;$('spApply').disabled=true;if(base)await refresh();else render();});
    $('spRecipe').onchange=lists;
    for(const [id,isPano] of [['spStill',false],['spPano',true]])$(id).onchange=()=>wrapped(async()=>{const file=$(id).files[0];if(!file)return;const decoded=await C.decode(file,isPano),point=(base||api.getMove()).waypoints[+$('spPoint').value]||{pitch:0,yaw:0};if(isPano){scene.panorama={url:decoded.url,pitch:point.pitch,yaw:point.yaw};}else{if(scene.references.length>=24)throw Error('24 reference stills maximum.');scene.references.push({...decoded,name:file.name.slice(0,128),pitch:point.pitch,yaw:point.yaw,hfov:scene.hfov});}scene=C.validate(scene);fields();lists();render();$(id).value='';status('Reference added locally. Check alignment and save this location.');});
    $('spImport').onchange=()=>wrapped(async()=>{const f=$('spImport').files[0];if(!f)return;if(f.size>C.MAX_BYTES)throw Error('Location file exceeds 24 MB.');const imported=C.validate(JSON.parse(await f.text()));if(!confirm('Replace the working location with this file? Save current edits first.'))return;scene=imported;fields();invalidate();lists();$('spImport').value='';status('Location imported locally. Re-check alignment, then load the current shot.');});
    const resized=new ResizeObserver(()=>draw());resized.observe(root.querySelector('.sp-stage'));
    const visibility=()=>{if(document.hidden)pause();};document.addEventListener('visibilitychange',visibility);
    tab('location');lists();render();locations().catch(e=>status(e.message));
    return {activate:()=>{lists();view?.setActive(true);},pause:()=>{pause();view?.setActive(false);},invalidate,dispose:()=>{pause();ticket++;view?.dispose();resized.disconnect();document.removeEventListener('visibilitychange',visibility);},getState:()=>({time,playing,analysis:!!analysis,variant:!!variant,view:!!view,scene:C.validate(scene)}),stats:()=>view?.stats()};
  };
})();
